# Numpy Assignment


## QNo.1 Function to create vander matrix

In [8]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4])

In [25]:
# function to create vander matrix
def vander(x,bool):
        N = len(x)
        if bool == True:
            print(np.column_stack([x**(N-1-i) for i in reversed(range(N))]))
        else:
            print(np.column_stack([x**(N-1-i) for i in range(N)]))

vander(arr,True)

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]


In [26]:
vander(arr,False)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


## QNo.2 Moving avg sequence

In [30]:
lst = [3,5,7,2,8,10,11,65,72,81,99,100,150]

In [31]:
inputarr = np.array(lst)

In [33]:
type(inputarr)

numpy.ndarray

In [47]:
def mvngavg(arr,k):
    size = len(arr)
    seqarrlen = size-k+1
    print(np.column_stack(arr[i:i+k].mean() for i in range(seqarrlen)))
    
mvngavg(inputarr,3)

[[  5.           4.66666667   5.66666667   6.66666667   9.66666667
   28.66666667  49.33333333  72.66666667  84.          93.33333333
  116.33333333]]


C:\Users\thamatak\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  after removing the cwd from sys.path.
